### ISSUE TITLE
%player_block_above% variable/placeholder is not working

### ISSUE THREAD

**Issue by Fenix5fire** [Ajneb97/ConditionalEvents#10]
%player_block_above% variable/placeholder is not working, but still in wiki
Its possible to use %player_block__below% with negative value instead, so I thought that it's inteded and just not changed in documentation

![image](https://user-images.githubusercontent.com/62252856/202862072-e7aa60ca-1591-4009-a66a-f7e74fa2676a.png)

- '%playerblock_below_-1% == ACACIA_LEAVES'
probably same as
- '%playerblock_above_1% == ACACIA_LEAVES'

but the last one isnt working

![image](https://user-images.githubusercontent.com/62252856/202862000-76fe3f7e-26bb-419c-a59f-83854df764fb.png)
```
test:
    type: repetitive
    repetitive_time: 20
    conditions:
    - '%playerblock_above_2% == ACACIA_LEAVES'
    actions:
        default:
        - 'message: %playerblock_above_2%'
    enabled: true
```
