### ISSUE TITLE
[BUG] Cannot execute on call event conditions

### ISSUE THREAD

**Issue by DrJekyllH** [Ajneb97/ConditionalEvents#101]
I asked a similar question in the Discord community chat, but it was fully ignored, so I am posting it here.

When calling eventA below, why is the “default” of eventB executed regardless of the value of %rnd%?
Can't excute be used in conditons for the call event?

%rng_1,80% is a PlaceholderAPI that generates random numbers from 1 to 80. In other words, %rnd% should not contain 0, but eventB executes default.

```
Events:
  eventA:
    type: call
    actions:
      default:
        - "call_event: eventB;%rnd%=%rng_1,80%"
      
  eventB:
    type: call
    conditons:
      - "%rnd% == 0"
      - "%rnd% == 1 execute allay"
(snip)
    actions:
      default:
        - "message: default"
        - "message: %rnd%"
      allay:
        - "message: hello"
      armadillo:
(snip)
```
