### ISSUE TITLE
[Bug] Offhand Swapping Issues

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#107]
The `player_click_inventory` and `player_swap_hand` events don’t detect when the offhand is switched or clicked using a hotkey. For example, if I wanted to disable the offhand entirely, I couldn't. If a player places an item in the inventory crafting menu, hovers over it, and presses F (the default offhand hotkey), it doesn’t trigger a click or an offhand swap event.

**Comment by Ajneb97** [comment]
Could you send me your player_click_inventory event config?

**Comment by KhrysAK47** [comment]
```
  OFFHAND_DISABLER:
    type: player_click_inventory
    conditions:
    - '%inventory_type% equals PLAYER'
    - '%slot% equals 40'
    actions:
      default:
      - 'cancel_event: true'
    enabled: true
  OFFHAND_DEBUG:
    type: player_click_inventory
    conditions:
    - '%inventory_type% equals PLAYER'
    actions:
      default:
      - 'to_all: message: &fInventory Type: %inventory_type%'
      - 'to_all: message: &fSlot: %slot%'
      - 'to_all: message: &fClick Type: %click_type%'
    enabled: true
```

**Comment by Ajneb97** [comment]
When you press F on an item. do the events get activated? Use /ce debug <event>

**Comment by KhrysAK47** [comment]
No.

**Comment by Ajneb97** [comment]
I'll have to take a look

**Comment by Ajneb97** [comment]
Tested on 1.21.4 with this event:
```
example5:
    type: player_click_inventory
    actions:
      default:
      - "message: Clicking %inventory_type% %click_type%"
```

When pressing F (moving the item to the offhand) the message is sent correctly. The same goes to player_swap_hand event, it is working correctly. Even so, if I add a cancel_event: true action, it is impossible to move an item to the offhand.
