### ISSUE TITLE
Detection error with "Inventory Move" event

### ISSUE THREAD

**Issue by DieG0Dig** [Ajneb97/ConditionalEvents#25]
I am using Paper for version 1.20 and when testing with the item move event from the debug when moving items from the player's inventory in survival it detects it as type "CRAFTING" instead of "PLAYER" as the Spigot documentation says.

This is the event I did.

```
  item:
    type: item_move
    conditions:
    - "%inventory_type% == PLAYER"
    - '%slot% == 1'
    actions:
      default:
      - "message: &cNope!"
      - "cancel_event: true"
```
