### ISSUE TITLE
Error: Could not pass event

### ISSUE THREAD

**Issue by Tanerx** [Ajneb97/ConditionalEvents#43]
I'm testing to cancel PlayerPickupItemEvent event but I'm getting a error. What is the right config for this ?

![image](https://github.com/Ajneb97/ConditionalEvents/assets/32717109/21b8f881-e91a-4def-82c4-61398cc8a1c2)

```
  PickupItemEvent:
    type: custom
    custom_event_data:
      event: org.bukkit.event.player.PlayerPickupItemEvent
      player_variable: getPlayer()
      variables_to_capture:
      - 'getItem().getItemStack().getLocation().getWorld().getName()'
    actions:
      default:
      - 'message: &cPickupItemEvent'
```
Full server log: https://mclo.gs/MeL6zzc

Thanks.

**Comment by Tanerx** [comment]
> ItemStack class

I'm trying to do it this way to learn more about custom type. I changed it as below and I still get the error. I would appreciate it if you could show me where I made a mistake.

```
  PickupItemEvent:
    type: custom
    custom_event_data:
      event: org.bukkit.event.player.PlayerPickupItemEvent
      player_variable: getPlayer()
      variables_to_capture:
      - 'getItem().getItemStack().getWorld().getName()'
    actions:
      default:
      - 'message: &cPickupItemEvent'
      - 'cancel_event: true'
```
![image](https://github.com/Ajneb97/ConditionalEvents/assets/32717109/1b472331-1f07-42da-86bf-6b01cac60a55)
