### ISSUE TITLE
ConditionalEvent's cancel_event feature does not work on MythicMobs

### ISSUE THREAD

**Issue by hero23550** [Ajneb97/ConditionalEvents#46]
1.19.4 PaperMC server
ConditonalEvents 4.45.4
MythicMobs v5.5.1

- Make a event similar to the following:
```
  event2:
    type: item_interact
    conditions:
    - '%item% == PIG_SPAWN_EGG and %action_type% == RIGHT_CLICK execute remove'
    actions:
      remove:
      - 'cancel_event: true'
    enabled: true
```
- Get any boss egg with /mm egg get [mob_name] <amount>
- Right click the egg and see the cancel_event feature fail

_PS: i am reporting this since i am trying to make a boss spawn limiter using boss eggs (like if players already summoned one boss with the egg they cant summon another until the alive one dies or despawns. [i have almost achieved this but cancel_event doesnt seem to work on mythicmobs] )_
