### ISSUE TITLE
%player% placeholder doesn't parse on 'to_target' action

### ISSUE THREAD

**Issue by Kaidenleaf** [Ajneb97/ConditionalEvents#47]
From version 4.45.2 and above, the placeholder of %player% in the to_target action doesn't parse.

You can try it with the example from the [player_attack event](https://ajneb97.gitbook.io/conditionalevents/event-types/player-events#player-attack):
```yml
example:
  type: player_attack
  conditions:
  - '%victim% == PLAYER'
  - '%item% == DIAMOND_SWORD'
  - '%item_name% == Super Sword'
  - '%random_1-10% >= 8'
  actions:
    default:
    - 'message: &aYour diamond sword poison effect was activated! &6%target:player_name% &ais now poisoned!'
    - 'to_target: give_potion_effect: POISON;120;1'
    - 'to_target: message: &cYou were poisoned by &e%player%&c!'
```
On version 4.45.1:
![image](https://github.com/Ajneb97/ConditionalEvents/assets/129576524/03793010-b99b-465d-a927-d73688c94636)

On version 4.45.2 and above:
![Screenshot 2024-01-01 162845](https://github.com/Ajneb97/ConditionalEvents/assets/129576524/9054b30b-6333-4f33-b9d0-7414ca70f3e0)
