### ISSUE TITLE
Removing non-existent effect from player causes error

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#50]
We have an Event that removes specific potion effects from player upon death just to ensure they don't have it, and it seems that if they die without the effect the following error is sent: https://pastebin.com/w1Z0dbwY

```
  WORLDGUARD_DEATH:
    type: player_death
    conditions:
    - '%worldguard_region_name% contains floor'
    actions:
      default:
      - 'console_command: svar reset %worldguard_region_name% silent:true'
      - 'wait_ticks: 5'
      - 'console_command: espawn %player_name%'
      - 'wait_ticks: 20'
      - 'remove_potion_effect: BLINDNESS'
      - 'remove_potion_effect: SLOWNESS'
    enabled: true
```
