### ISSUE TITLE
Error when using command

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#59]
https://pastebin.com/apjd9vsc

Command:
```
  PING:
    type: player_command
    conditions:
    - '%main_command% equalsIgnoreCase /ping'
    actions:
      default:
      - 'cancel_event: true'
      - 'message: &aYou have &f%player_ping%ms&a.'
    enabled: true
```
