### ISSUE TITLE
remove_item_slot: HAND not working.

### ISSUE THREAD

**Issue by IceGames23** [Ajneb97/ConditionalEvents#63]
![image](https://github.com/Ajneb97/ConditionalEvents/assets/71414690/fac0ccd9-6fe8-4ab4-8fcd-0bb1aad417a1)

```
martinreparar:
    type: player_command
    conditions:
    - "%main_command% == /martinteste"
    - "%checkitem_namecontains:Peça Sobressalente,amt:5,mat:GHAST_TEAR% != yes execute erro"
    actions:
      default:
      - "cancel_event: true"
      - "execute_action_group: deucerto:80;deuerrado:20"
      erro:
      - "cancel_event: true"
      - 'message: &c '
      - 'message: &6 &lM&6.&lA&6.&lR&6.&lT&6.&lI&6.&lN&6.'
      - 'message: &7 Pera, ainda não possui as peças? Volte quando tiver as'
      - 'message: &7 5x &7[☣] &lPeça Sobressalente&7, aí eu poderei ajudar.'
      - 'message: &c '
      deucerto:
      - "remove_item: GHAST_TEAR;5" #%checkitem_remove_mat:GHAST_TEAR,nameequals:&7[☣] &lPeça Sobressalente,amt:5%
      - 'message: &c '
      - 'message: &6 &lM&6.&lA&6.&lR&6.&lT&6.&lI&6.&lN&6.'
      - 'message: &7 Meu querido, o processo deu certo!'
      - 'playsound: ANVIL_USE;10;1'
      - 'player_command_as_op: repairmartin'
      deuerrado:
      - "remove_item_slot: HAND;1"
      - "remove_item: GHAST_TEAR;5"
      - 'message: &c '
      - 'message: &6 &lM&6.&lA&6.&lR&6.&lT&6.&lI&6.&lN&6.'
      - 'message: &7 Então... O processo havia riscos, e acho que seu item &cquebrou&7, peço desculpas pelo ocorrido. Talvez da próxima nós possamos conseguir repará-lo.'
      - 'message: &c '
      - 'playsound: ITEM_BREAK;10;0.1'
```

remove_item_slot: HAND;1 it's not working, in debug it's saying that was executed the action, but the item stays in the hand.
Above it's the event that execute the action.

Spigot Version: 1.8.8
Plugin Version: 4.47.4
