### ISSUE TITLE
[Suggestion] Add variable to retrieve UUID of victim in victim-related events

### ISSUE THREAD

**Issue by Feniksovich** [Ajneb97/ConditionalEvents#73]
Add variable `%victim_uuid%` in victim-related events like `%entity_uuid%` in entity-related events.

**Comment by Feniksovich** [comment]
Closing an issue without any explanation is pretty rude. A quick comment would be appreciated next time.

**Comment by Ajneb97** [comment]
This was added a long time ago https://ajneb97.gitbook.io/conditionalevents/global-variables#entity-variables

**Comment by Feniksovich** [comment]
> This was added a long time ago https://ajneb97.gitbook.io/conditionalevents/global-variables#entity-variables

It's not the same things actually. There is no variable to retrieve UUID of attacked entity for `player_attack` event type for example.  `%entity_uuid%` never seems to get parsed here and for any "victim-related" events too I guess.

```yaml
  realms_poster_button_lmb:
    type: player_attack
    conditions:
    - '%victim% == INTERACTION'
    - '%entity_uuid% == 198bff12-cbc5-41c3-afe1-a5b25d25c324' # doesn't work
    # ...
```
