### ISSUE TITLE
[Feature Request] plugin_reload event

### ISSUE THREAD

**Issue by Clexus** [Ajneb97/ConditionalEvents#78]
I have some events that set variable to true and "wait" and set to false.
But when the plugin reloaded, wait actions will stop, and the variables keep the true value.
I need a plugin_reload event, it's a player event

**Comment by Clexus** [comment]
reload event example or wait event example?
```
syqx:
    type: call
    conditions:
    - '%mycommand_playerdata_tiaozhaning% != yes'
    actions:
      default:
      - 'player_command_as_op: setplayerdata %player% tiaozhaning yes'
      - 'player_command_as_op: setplayerdata %player% tiaozhan.syqx.wh 0'
      - 'player_command_as_op: setplayerdata %player% tiaozhan.syqx.slss 0'
      - 'wait: 300'
      - 'call_event: syqx2'
  syqx2:
    type: call
    conditions:
    - '%mycommand_playerdata_tiaozhaning% == yes'
    - '%mycommand_playerdata_tiaozhan.syqx.wh% < 100 or %mycommand_playerdata_tiaozhan.syqx.wh% < 100 execute fail'
    - '%mycommand_playerdata_tiaozhan.syqx.wh% >= 100 and %mycommand_playerdata_tiaozhan.syqx.wh% >= 100 execute suc'
    actions:
      fail:
      - 'message: &c&l挑战失败...你只杀了&4&l%mycommand_playerdata_tiaozhan.syqx.wh%&c&l个亡魂和&4&l%mycommand_playerdata_tiaozhan.syqx.slss%&c&l个死灵术师'
      - 'player_command_as_op: setplayerdata %player% tiaozhaning no'
      - 'player_command_as_op: addplayerdata %player% tiaozhan.fail.all 1'
      - 'player_command_as_op: addplayerdata %player% tiaozhan.fail.syqx 1'
      suc:
      - 'message: &e&l挑战成功！你杀了&4&l%mycommand_playerdata_tiaozhan.syqx.wh%&e&l个亡魂和&4&l%mycommand_playerdata_tiaozhan.syqx.slss%&e&l个死灵术师！'
      - 'player_command_as_op: setplayerdata %player% tiaozhaning no'
      - 'player_command_as_op: addplayerdata %player% tiaozhan.suc.all 1'
      - 'player_command_as_op: addplayerdata %player% tiaozhan.suc.syqx 1'
      - 'console_command: eco give %player% 12000'
      - 'console_command: p give %player% 200'
```
When I reload plugin, wait action in "syqx" will stop, and tiaozhaning variable keep the "yes" value
Players should rejoin to set them to false automatically
