### ISSUE TITLE
[Suggestion] ServerVariables Support

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#80]
Make a direct addition of ServerVariables, in which we could do things like:

```
  TEST:
    type: player_kill
    conditions: []
    actions:
      default:
      - 'servervariables: <add/remove/set> <player> <variable_id> <new_variable> <silent:true/false>'
    enabled: true
```
