### ISSUE TITLE
Bug event equip armor

### ISSUE THREAD

**Issue by GreatGoal0** [Ajneb97/ConditionalEvents#88]
Hola tengo un evento que al equipar una armadura con un nombre si no cumple las condiciones cancele el evento de equipar la armadura (que no se pueda equipar la armor) lo que si funciona, el detalle es que si te equipas la armadura desde el inventario armadura desaparece (se come la armadura)

```yml
Events:
  armor_level_10:
    type: player_armor
    conditions:
    - '%equip_type% == EQUIP'
    - '%item_name% contains nivel 10'
    - '%luckperms_meta_level% < 10'
    actions:
      default:
      - 'cancel_event: true'
```

![IMG_20240901_000142](https://github.com/user-attachments/assets/da89a41c-d913-4af2-9bc7-c510e24aecc2)
