### ISSUE TITLE
[BUG] skeleton_skull is not recognized on player_armor

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#89]
Hello! I recently encountered an issue where all of the mob heads with the exception of skeleton_skull are recognized in the player_armor events, you can use the following configuration to test it and see that it will not work:

```
  TEST:
    type: player_armor
    conditions:
    - '%equip_type% == EQUIP or %equip_type% == UNEQUIP'
    actions:
      default:
      - 'to_all: message: &aSuccess'
    enabled: true
```
