### ISSUE TITLE
[BUG] drag clicking is not preventable on player_armor

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#90]
You can't prevent armor placement by drag clicking in any way if it has multiple items, here a video on how to do it: https://imgur.com/a/yh5ASBc

```
  TEST:
    type: player_armor
    conditions: []
    actions:
      default:
      - 'cancel_event: true'
    enabled: true
```
