### ISSUE TITLE
Repetitive events remain after error even after fixing configuration

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#91]
Repetitive events that are present in the server when you do a config mistake remain, let's say I have:

```
  TEST:
    type: repetitive
    repetitive_time: 40
    conditions: []
    actions:
      default:
      - 'message: TEST'
    enabled: true
```

- Then we mess the config for a moment, like adding two ', or similar, then /ce reload (it will say error).
- Then we fix that error and do /ce reload again.
- Change the message from TEST to anything else.
- /ce reload again
- We will have both actions being executed despite the first one not existing anymore.
